<?php

namespace ContainerFgjn3Hz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JNeVz5RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jNeVz5R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jNeVz5R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'principalRepository' => ['privates', 'App\\Repository\\PrincipalRepository', 'getPrincipalRepositoryService', true],
        ], [
            'principalRepository' => 'App\\Repository\\PrincipalRepository',
        ]);
    }
}
