<?php

namespace ContainerFgjn3Hz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V_9K5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v.9__k5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v.9__k5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'subCategory' => ['privates', '.errored..service_locator.v.9__k5.App\\Entity\\SubCategory', NULL, 'Cannot autowire service ".service_locator.v.9__k5": it references class "App\\Entity\\SubCategory" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'subCategory' => 'App\\Entity\\SubCategory',
        ]);
    }
}
