<?php

namespace ContainerFgjn3Hz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bt4JTv2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bt4JTv2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bt4JTv2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'subCategory' => ['privates', '.errored..service_locator.Bt4JTv2.App\\Entity\\SubCategory', NULL, 'Cannot autowire service ".service_locator.Bt4JTv2": it references class "App\\Entity\\SubCategory" but no such service exists.'],
        ], [
            'subCategory' => 'App\\Entity\\SubCategory',
        ]);
    }
}
