<?php

namespace ContainerFgjn3Hz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v.9__k5.App\Entity\SubCategory' shared service.
     *
     * @return \App\Entity\SubCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.v.9__k5": it references class "App\\Entity\\SubCategory" but no such service exists.');
    }
}
