<?php

namespace ContainerQuQ5xHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5vlV5XkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5vlV5Xk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5vlV5Xk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contacto' => ['privates', '.errored..service_locator.5vlV5Xk.App\\Entity\\Contacto', NULL, 'Cannot autowire service ".service_locator.5vlV5Xk": it references class "App\\Entity\\Contacto" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'contacto' => 'App\\Entity\\Contacto',
            'entityManager' => '?',
        ]);
    }
}
