<?php

namespace ContainerQuQ5xHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XBrugRPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xBrugRP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xBrugRP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'principal' => ['privates', '.errored..service_locator.xBrugRP.App\\Entity\\Principal', NULL, 'Cannot autowire service ".service_locator.xBrugRP": it references class "App\\Entity\\Principal" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'principal' => 'App\\Entity\\Principal',
        ]);
    }
}
