<?php

namespace ContainerQuQ5xHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5vlV5Xk.App\Entity\Contacto' shared service.
     *
     * @return \App\Entity\Contacto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5vlV5Xk": it references class "App\\Entity\\Contacto" but no such service exists.');
    }
}
