<?php

namespace ContainerQuQ5xHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ContactoType' shared autowired service.
     *
     * @return \App\Form\ContactoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ContactoType.php';

        return $container->privates['App\\Form\\ContactoType'] = new \App\Form\ContactoType();
    }
}
