<?php

namespace ContainerQuQ5xHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrincipal2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xBrugRP.App\Entity\Principal' shared service.
     *
     * @return \App\Entity\Principal
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xBrugRP": it references class "App\\Entity\\Principal" but no such service exists.');
    }
}
