<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFgjn3Hz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFgjn3Hz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFgjn3Hz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFgjn3Hz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFgjn3Hz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fgjn3Hz',
    'container.build_id' => 'd061c791',
    'container.build_time' => 1643870769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFgjn3Hz');
